### ISSUE TITLE
java.io.IOException:Cannot run program "/date/user/0/com.googl...

### ISSUE THREAD

**Issue by Cypher-ZT** [IvanVolosyuk/diskusage#55]
hi, i really like this  app , but there is a  exception is always  happening . "java.io.IOException:Cannot run program "/date/user/0/com.googl... "   i see the rest of them’
I'm a  Java beginner. your code is too complex for me  i  cannot  resolve it 
oh  my phone is oneplus 5t  ，android 8.1
forgive my bad English ；

**Comment by Condor70** [comment]
Just updated my Oneplus One phone from Cyanogen OS 6.0.1 to Lineage OS 15.1 and updated to DiskUsage 4.0.2 for Oreo.
Now I'm getting this error also every time.

**Comment by nnn1590** [comment]
`adb logcat`:
```logcat
11-11 14:06:38.722 16331 17886 E diskusage: java.io.IOException: Cannot run program "/data/user/0/com.google.android.diskusage/app_binary/scan5": error=13, Permission denied
11-11 14:06:38.722 16331 17886 E diskusage: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
11-11 14:06:38.722 16331 17886 E diskusage: 	at java.lang.Runtime.exec(Runtime.java:692)
11-11 14:06:38.722 16331 17886 E diskusage: 	at java.lang.Runtime.exec(Runtime.java:560)
11-11 14:06:38.722 16331 17886 E diskusage: 	at com.google.android.diskusage.datasource.fast.NativeScannerStream$Factory.runScanner(NativeScannerStream.java:78)
11-11 14:06:38.722 16331 17886 E diskusage: 	at com.google.android.diskusage.datasource.fast.NativeScannerStream$Factory.create(NativeScannerStream.java:62)
11-11 14:06:38.722 16331 17886 E diskusage: 	at com.google.android.diskusage.datasource.fast.DefaultDataSource.createNativeScanner(DefaultDataSource.java:76)
11-11 14:06:38.722 16331 17886 E diskusage: 	at com.google.android.diskusage.NativeScanner.scan(NativeScanner.java:187)
11-11 14:06:38.722 16331 17886 E diskusage: 	at com.google.android.diskusage.DiskUsage.scan(DiskUsage.java:604)
11-11 14:06:38.722 16331 17886 E diskusage: 	at com.google.android.diskusage.LoadableActivity$2.run(LoadableActivity.java:133)
11-11 14:06:38.722 16331 17886 E diskusage: Caused by: java.io.IOException: error=13, Permission denied
11-11 14:06:38.722 16331 17886 E diskusage: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
11-11 14:06:38.722 16331 17886 E diskusage: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
11-11 14:06:38.722 16331 17886 E diskusage: 	at java.lang.ProcessImpl.start(ProcessImpl.java:128)
11-11 14:06:38.722 16331 17886 E diskusage: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
11-11 14:06:38.722 16331 17886 E diskusage: 	... 8 more
11-11 14:06:38.722 16331 17886 D DiskUsage: exception in scan!
```

あまり良い解決策ではないですが、次のコマンドを実行することで回避できました(root必須):
It's not a very good solution, but it could be avoided by running the following command (root is required):
```bash
su -c "while :; do chmod +x /data/user/0/com.google.android.diskusage/app_binary/scan5; done"
```

Android 8.0.0

Google 翻訳によって日本語から英語に翻訳されました。
Translated from Japanese to English by Google Translate.

**Comment by WhiredPlanck** [comment]
You could see my explain for this issue: https://github.com/IvanVolosyuk/diskusage/issues/65#issuecomment-1086866807
